# This is a basic workflow to help you get started with Actions
name: MyFirstCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GitAction
    steps:
      - run: cat /etc/os-release

      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '11'
        run: java --version  

      - name: Download dependencies
        run: mvn dependency:go-offline

      - name: Build project
        run: mvn compile

      - name: Run unit tests
        run: mvn test
